---
apiserver_nginx_pool: 127.0.0.1:443
deployment_mode: binary
kraken_services: skydns|atlas/skydns-0.1.0 prometheus|atlas/prometheus-0.1.0 kubedash|atlas/kubedash-0.1.0 monitoring|atlas/cluster-monitoring-0.1.0
kraken_services_repos: atlas|http://atlas.cnct.io
tiller_rc: tiller-rc
tiller_image: quay.io/samsung_cnct/tiller
helm_image: quay.io/samsung_cnct/helm
thirdparty_scheduler:
services:
  command_passwd: "{{command_passwd}}"
  dockercfg_base64: "{{dockercfg_base64}}"
  master_ip: "{{master_private_ip}}"
  apiserver_ip: "{{master_private_ip}}"
  controller_manager_ip: "{{master_private_ip}}"
  scheduler_ip: "{{master_private_ip}}"
  etcd_ip: "{{etcd_private_ip}}"
  dns_domain: "{{dns_domain}}"
nginx:
  kubernetes_api_proxy_uri_regexes:
    - "/api/v1/proxy/namespaces/([^/]+)/(pods|services)"
    - "/api/v1/proxy/nodes"
    - "/api/v1/namespaces/([^/]+)/(pods|services)/([^/]+)/proxy"
    - "/api/v1/nodes/([^/]+)/proxy"
