---
apiserver_nginx_pool: 127.0.0.1:443
deployment_mode: binary
nginx:
  kubernetes_api_proxy_uri_regexes:
    - "/api/v1/proxy/namespaces/([^/]+)/(pods|services)"
    - "/api/v1/proxy/nodes"
    - "/api/v1/namespaces/([^/]+)/(pods|services)/([^/]+)/proxy"
    - "/api/v1/nodes/([^/]+)/proxy"
