---
- name: Clean up releases
  become: yes
  shell: >
    docker run --rm -v {{ helm_home }}:/helm-home -v {{ kubeconfig | expanduser }}:/root/.kube/config {{ helm_image }} delete {{ item.split('|')[0] }}
  with_items: "{{ kraken_services.split(' ') }}"
  ignore_errors: yes

- name: 
  become: yes
  stat: path={{ service_configs_dir }}/{{ item.split('|')[0] }}.{{ service_configs_ext }}.yaml
  with_items: "{{ kraken_services.split(' ') }}"
  register: defined_services_values

- name: Install charts without user defined values
  become: yes
  shell: >
    docker run --rm -v {{ helm_home }}:/helm-home -v {{ kubeconfig | expanduser }}:/root/.kube/config {{ helm_image }} install {{ item.1.split('|')[1] }} --name {{ item.1.split('|')[0] }} --values {{ service_configs_dir }}/default-helm-values.yaml
  with_together:
    - {{ defined_services_values.results }}
    - {{ kraken_services.split(' ') }}
  when:
    - item.0.exist == false

- name: Install charts with user defined values
  become: yes
  shell: >
    docker run --rm -v {{ helm_home }}:/helm-home -v {{ kubeconfig | expanduser }}:/root/.kube/config {{ helm_image }} install {{ item.1.split('|')[1] }} --name {{ item.1.split('|')[0] }} --values {{ service_configs_dir }}/{{ item.1.split('|')[0] }}.{{ service_configs_ext }}.yaml
  with_together:
    - {{ defined_services_values.results }}
    - {{ kraken_services.split(' ') }}
  when:
    - item.0.exist == true
