---
- name: Clean up releases
  become: yes
  shell: >
    /usr/bin/docker run --rm 
    -v {{ helm_home }}:/helm-home 
    --volumes-from kraken_data 
    -e KUBECONFIG={{ kubeconfig }} {{ helm_image }} 
    delete {{ item.split('|')[0] }}
  with_items: "{{ kraken_services.split(' ') }}"
  ignore_errors: yes

- name: Stat all the custom user value files for services charts
  stat: path={{ service_configs_dst }}/{{ item.split('|')[0] }}.{{ service_configs_ext }}.yaml
  with_items: "{{ kraken_services.split(' ') }}"
  register: defined_services_values

- name: Install charts without user defined values
  become: yes
  shell: >
    /usr/bin/docker run --rm 
    -v {{ helm_home }}:/helm-home 
    --volumes-from kraken_data -e KUBECONFIG={{ kubeconfig }} {{ helm_image }} 
    install {{ item.1.split('|')[1] }} --name {{ item.1.split('|')[0] }} --values {{ service_configs_dst }}/default-helm-values.yaml
  with_together:
    - "{{ defined_services_values.results }}"
    - "{{ kraken_services.split(' ') }}"
  when: item.0.stat.exists == false

- name: Install charts with user defined values
  become: yes
  shell: >
    /usr/bin/docker run --rm 
    -v {{ helm_home }}:/helm-home 
    --volumes-from kraken_data 
    -e KUBECONFIG={{ kubeconfig }} {{ helm_image }} 
    install {{ item.1.split('|')[1] }} --name {{ item.1.split('|')[0] }} --values {{ service_configs_dst }}/{{ item.1.split('|')[0] }}.{{ service_configs_ext }}.yaml
  with_together:
    - "{{ defined_services_values.results }}"
    - "{{ kraken_services.split(' ') }}"
  when: item.0.stat.exists == true
