---
- name: create a temp path kraken services locally
  local_action: shell mktemp -d -t services.{{ inventory_hostname }}.XXXXXXXXXX
  register: services_local_path

- name: See if tiller rc if present
  shell: >
    /usr/bin/kubectl --kubeconfig={{ kubeconfig | expanduser }} get rc {{ tiller_rc }}
  register: tiller_present
  ignore_errors: yes

- name: Clean up releases
  shell: >
    /usr/bin/docker run --rm
    -v {{ helm_home }}:/helm-home
    --volumes-from kraken_data
    -e KUBECONFIG={{ kubeconfig }} {{ helm_image }}
    delete {{ item.split('|')[0] }}
  with_items: "{{ kraken_services.split(' ') }}"
  ignore_errors: yes
  when: tiller_present|success

- name: Clean up tiller rc if present
  shell: >
    /usr/bin/kubectl --kubeconfig={{ kubeconfig | expanduser }} delete rc {{ tiller_rc }}
  when: tiller_present|success

- name: Delete all service namespaces
  shell: >
    /usr/bin/kubectl --kubeconfig={{ kubeconfig | expanduser }} delete namespace {{ item }}
  with_items: "{{ kraken_services_namespaces.split(' ') }}"
  ignore_errors: yes

- name: Create all service namespaces
  shell: >
    /usr/bin/kubectl --kubeconfig={{ kubeconfig | expanduser }} create namespace {{ item }}
  with_items: "{{ kraken_services_namespaces.split(' ') }}"

- name: Create Helm home
  file: >
    path={{ helm_home }}
    state=directory

- name: Init helm
  shell: >
    /usr/bin/docker run --rm
    -v {{ helm_home }}:/helm-home
    --volumes-from kraken_data
    -e KUBECONFIG={{ kubeconfig }} {{ helm_image }}
    init --tiller-image {{ tiller_image }}

- name: Remove helm repositories
  shell: >
    /usr/bin/docker run --rm
    -v {{ helm_home }}:/helm-home
    --volumes-from kraken_data
    -e KUBECONFIG={{ kubeconfig }} {{ helm_image }}
    repo remove {{ item.split('|')[0] }}
  with_items: "{{ kraken_services_repos.split(' ') }}"
  ignore_errors: yes

- name: Add helm repositories
  shell: >
    /usr/bin/docker run --rm
    -v {{ helm_home }}:/helm-home
    --volumes-from kraken_data
    -e KUBECONFIG={{ kubeconfig }} {{ helm_image }}
    repo add {{ item.split('|')[0] }} {{ item.split('|')[1] }}
  with_items: "{{ kraken_services_repos.split(' ') }}"

- name: Get all user provided service configs
  stat: path={{item}}
  with_fileglob: "{{ service_configs }}"
  register: user_configs

- name: Fetch all the values files
  run_once: true
  fetch: >
    src={{ item }}
    dest={{ services_local_path }}/
    flat=yes
    fail_on_missing=yes
  with_fileglob: "{{ service_configs_src }}"

- name: Create configs destination
  file: >
    path={{ service_configs_dst }}
    state=directory

- name: Render helm values files for all deployment names in kraken_services unless already present
  template: src={{ item }} dest={{ service_configs_dst }}/{{ item | basename }}.yaml
  with_fileglob: "{{ services_local_path }}/*.{{ service_configs_ext }}"

- name: Create default values file
  template: src=helm-values.yaml.jinja2 dest={{ service_configs_dst }}/default-helm-values.yaml