---
- name: Clean up releases
  become: yes
  shell: >
    docker run --rm -v /root/.helm:/helm-home -v {{ controller_manager_settings.kubeconfig | expanduser }}:/root/.kube/config {{ helm_image }} delete {{ item.split('|')[0] }}
  with_items: "{{ kraken_services.split(' ') }}"
  ignore_errors: yes

- name: Install charts
  become: yes
  shell: >
    docker run --rm -v /root/.helm:/helm-home -v {{ controller_manager_settings.kubeconfig | expanduser }}:/root/.kube/config {{ helm_image }} install {{ item.split('|')[1] }} --name {{ item.split('|')[0] }} --values /root/helm-values.yaml
  with_items: "{{ kraken_services.split(' ') }}"
