---
- name: Clean up releases
  shell: >
    docker run --rm -v /root/.helm:/helm-home -v {{ controller_manager_settings.kubeconfig | expanduser }}:/root/.kube/config {{ helm_image }} delete {{ item.split('|')[0] }}
  with_items: "{{ kraken_services.split(' ') }}"
  ignore_errors: yes

- name: Install charts
  shell: >
    docker run --rm -v /root/.helm:/helm-home -v {{ controller_manager_settings.kubeconfig | expanduser }}:/root/.kube/config {{ helm_image }} install {{ item.split('|')[1] }} --name {{ item.split('|')[0] }}
  with_items: "{{ kraken_services.split(' ') }}"
